### ISSUE TITLE
Need Postgres support

### ISSUE THREAD

**Issue by jhriv** [ucsdlib/hyrax-demo#1]
`rake aborted!\nGem::LoadError: Specified 'postgresql' for database adapter, but the gem is not loaded. Add `gem 'pg'` to your Gemfile (and ensure its version is at the minimum required by ActiveRecord).`

I'm okay with a different. dev, branch

**Comment by mcritchlow** [comment]
I think we have those sorted via Slack, yes?

**Comment by mcritchlow** [comment]
Closing because I think we got past this issue, suspect there will be more :)

**Comment by jhriv** [comment]
The issue is resolved in the feature/demo branch, but not merged into master or anything else.
